name: Auto Check_in

on:
  # 定时触发：每天 UTC 时间 22:00（即北京时间次日早上 6:00）
  schedule:
    - cron: '31 22 * * *'
  # 支持手动触发工作流
  workflow_dispatch:

jobs:
  auto_signin:
    # 使用最新版的 Ubuntu 运行环境
    runs-on: ubuntu-latest

    # 设置环境变量（从 GitHub 仓库的 Secrets 中读取 Cookie 信息）
    env:
        # PTTIME A/B
        PTTIME_A_LOGGED_IN: ${{ secrets.PTTIME_A_LOGGED_IN }}
        PTTIME_A_CF_CLEARANCE: ${{ secrets.PTTIME_A_CF_CLEARANCE }}
        PTTIME_A_C_SECURE_UID: ${{ secrets.PTTIME_A_C_SECURE_UID }}
        PTTIME_A_C_SECURE_TRACKER_SSL: ${{ secrets.PTTIME_A_C_SECURE_TRACKER_SSL }}
        PTTIME_A_C_SECURE_SSL: ${{ secrets.PTTIME_A_C_SECURE_SSL }}
        PTTIME_A_C_SECURE_PASS: ${{ secrets.PTTIME_A_C_SECURE_PASS }}
        PTTIME_A_C_SECURE_LOGIN: ${{ secrets.PTTIME_A_C_SECURE_LOGIN }}
        PTTIME_A_C_LANG_FOLDER: ${{ secrets.PTTIME_A_C_LANG_FOLDER }}

        PTTIME_B_LOGGED_IN: ${{ secrets.PTTIME_B_LOGGED_IN }}
        PTTIME_B_CF_CLEARANCE: ${{ secrets.PTTIME_B_CF_CLEARANCE }}
        PTTIME_B_C_SECURE_UID: ${{ secrets.PTTIME_B_C_SECURE_UID }}
        PTTIME_B_C_SECURE_TRACKER_SSL: ${{ secrets.PTTIME_B_C_SECURE_TRACKER_SSL }}
        PTTIME_B_C_SECURE_SSL: ${{ secrets.PTTIME_B_C_SECURE_SSL }}
        PTTIME_B_C_SECURE_PASS: ${{ secrets.PTTIME_B_C_SECURE_PASS }}
        PTTIME_B_C_SECURE_LOGIN: ${{ secrets.PTTIME_B_C_SECURE_LOGIN }}
        PTTIME_B_C_LANG_FOLDER: ${{ secrets.PTTIME_B_C_LANG_FOLDER }}

        # 1PTBA
        PTBA_X1_LOGGED_IN: ${{ secrets.PTBA_X1_LOGGED_IN }}
        PTBA_X1_CF_CLEARANCE: ${{ secrets.PTBA_X1_CF_CLEARANCE }}
        PTBA_X1_C_SECURE_UID: ${{ secrets.PTBA_X1_C_SECURE_UID }}
        PTBA_X1_C_SECURE_TRACKER_SSL: ${{ secrets.PTBA_X1_C_SECURE_TRACKER_SSL }}
        PTBA_X1_C_SECURE_SSL: ${{ secrets.PTBA_X1_C_SECURE_SSL }}
        PTBA_X1_C_SECURE_PASS: ${{ secrets.PTBA_X1_C_SECURE_PASS }}
        PTBA_X1_C_SECURE_LOGIN: ${{ secrets.PTBA_X1_C_SECURE_LOGIN }}
        PTBA_X1_C_LANG_FOLDER: ${{ secrets.PTBA_X1_C_LANG_FOLDER }}

        # PTTZONE
        PTZONE_X1_LOGGED_IN: ${{ secrets.PTZONE_X1_LOGGED_IN }}
        PTZONE_X1_CF_CLEARANCE: ${{ secrets.PTZONE_X1_CF_CLEARANCE }}
        PTZONE_X1_C_SECURE_UID: ${{ secrets.PTZONE_X1_C_SECURE_UID }}
        PTZONE_X1_C_SECURE_TRACKER_SSL: ${{ secrets.PTZONE_X1_C_SECURE_TRACKER_SSL }}
        PTZONE_X1_C_SECURE_SSL: ${{ secrets.PTZONE_X1_C_SECURE_SSL }}
        PTZONE_X1_C_SECURE_PASS: ${{ secrets.PTZONE_X1_C_SECURE_PASS }}
        PTZONE_X1_C_SECURE_LOGIN: ${{ secrets.PTZONE_X1_C_SECURE_LOGIN }}
        PTZONE_X1_C_LANG_FOLDER: ${{ secrets.PTZONE_X1_C_LANG_FOLDER }}

        # BTSCHOOL
        BTSCHOOL_X1_LOGGED_IN: ${{ secrets.BTSCHOOL_X1_LOGGED_IN }}
        BTSCHOOL_X1_CF_CLEARANCE: ${{ secrets.BTSCHOOL_X1_CF_CLEARANCE }}
        BTSCHOOL_X1_C_SECURE_UID: ${{ secrets.BTSCHOOL_X1_C_SECURE_UID }}
        BTSCHOOL_X1_C_SECURE_PASS: ${{ secrets.BTSCHOOL_X1_C_SECURE_PASS }}
        BTSCHOOL_X1_C_SECURE_SSL: ${{ secrets.BTSCHOOL_X1_C_SECURE_SSL }}
        BTSCHOOL_X1_C_SECURE_TRACKER_SSL: ${{ secrets.BTSCHOOL_X1_C_SECURE_TRACKER_SSL }}
        BTSCHOOL_X1_C_SECURE_LOGIN: ${{ secrets.BTSCHOOL_X1_C_SECURE_LOGIN }}
        BTSCHOOL_X1_C_LANG_FOLDER: ${{ secrets.BTSCHOOL_X1_C_LANG_FOLDER }}
        BTSCHOOL_X1_SL_SESSION: ${{ secrets.BTSCHOOL_X1_SL_SESSION }}

    steps:
      # 第一步：拉取当前仓库代码
      - name: 检出代码仓库
        uses: actions/checkout@v3

      # 第二步：设置 Python 环境（使用 Python 3.12）
      - name: 安装 Python 环境
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      # 第三步：安装所需 Python 库（仅安装 cloudscraper，dotenv 在 GitHub 不使用）
      - name: 安装依赖库
        run: |
          pip install --upgrade pip
          pip install cloudscraper

      # 第四步：运行签到脚本
      - name: 执行签到脚本
        run: python Check_in.py
